csgo_django_server/csgo_django_server/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csgo_django_server/task_manager/urls.py
from django.urls import path
from task_manager.views import (WorkerListView, home_view, ControlView, proxy_view, save_proxy, items_view,
                                items_save, home_status, update_data, LogoutView, upload_file, GetIPView,
                                LastPurchasesView)

urlpatterns = [
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path('', home_view, name='home'),
    path('control/', ControlView.as_view(), name='control'),
    path('proxy/', proxy_view, name='proxy'),
    path('save_proxy/', save_proxy, name='save_proxy'),
    path('items/', items_view, name='items'),
    path('items_save/', items_save, name='items_save'),
    path('home_status/', home_status, name='home_status'),
    path('update_data/', update_data, name='update_data'),
    path('upload_file/', upload_file, name='upload_file'),
    path('get_ip/', GetIPView.as_view(), name='get_ip'),
    path('last_purchases/', LastPurchasesView.as_view(), name='last_purchases'),
]

app_name = "task_manager"

csgo_django_server/templates/includes/header.html
{% load static %}

<div class="jumbotron">
  <div class="center-block">
    <img src="{% static 'it_company_header.jpeg' %}" class="img-thumbnail" alt="">
    <br>
      <button class="btn btn-default btn-md btn-block bottom"><i class="fa fa-trophy"><strong>Add task</strong></i></button>
    </a>
  </div>
</div>

csgo_django_server/templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

csgo_django_server/templates/includes/sidebar.html
{% block sidebar_login %}

  <div class="container-fluid">
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">

        <div class="navbar-header">
<!--          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
<!--            <span class="icon-bar"></span>-->
<!--            <span class="icon-bar"></span>-->
<!--            <span class="icon-bar"></span>-->
<!--          </button>-->

        </div>

        <div class="navbar-collapse collapse">
          {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'task_manager:home' %}">Task<i class="fa fa-circle"></i>MANAGE</a>

          <a class=" navbar-brand" href="/proxy/">Proxies </a>
          <a class="navbar-brand" href="/items/">Items</a>
          <a class="navbar-brand" href="/upload_file/">Attach</a>
          <div class="navbar-right navbar-brand"><span id="balans"></span>$</div>
          <a class="navbar-right navbar-brand" href="{% url 'logout' %}">Logout</a>

            {% if task_list %}
              <form  class="navbar-form center-block" role="search">
                <div class="form-group">
                  {% load crispy_forms_filters %}
                  {{ search_form|crispy }}
                </div>
                <button type="submit" class="btn btn-success">Search</button>
              </form>
            {% endif %}
          {% endif %}
        </div>

      </div>
    </div>
  </div>
{% endblock %}