csgo_django_server/csgo_django_server/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

csgo_django_server/task_manager/urls.py
from django.urls import path
from task_manager.views import (WorkerListView, home_view, ControlView, proxy_view, save_proxy, items_view,
                                items_save, home_status, update_data, LogoutView, upload_file, GetIPView,
                                LastPurchasesView)

urlpatterns = [
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path('', home_view, name='home'),
    path('control/', ControlView.as_view(), name='control'),
    path('proxy/', proxy_view, name='proxy'),
    path('save_proxy/', save_proxy, name='save_proxy'),
    path('items/', items_view, name='items'),
    path('items_save/', items_save, name='items_save'),
    path('home_status/', home_status, name='home_status'),
    path('update_data/', update_data, name='update_data'),
    path('upload_file/', upload_file, name='upload_file'),
    path('get_ip/', GetIPView.as_view(), name='get_ip'),
    path('last_purchases/', LastPurchasesView.as_view(), name='last_purchases'),
]

app_name = "task_manager"

csgo_django_server/task_manager/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class Worker(AbstractUser):
    username = models.CharField(max_length=69, null=True, unique=True)
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

csgo_django_server/task_manager/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.core import exceptions
from django.forms import BaseForm

from task_manager.models import Worker


class WorkerLoginForm(forms.Form, BaseForm):
    email = forms.EmailField(
        label="Email",
        max_length=50,
        widget=forms.EmailInput(
            attrs={"class": "form-control  mb-3", "placeholder": "Email"}
        ),
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control mb-3", "placeholder": "Password"}
        ),
    )


class WorkerRegisterForm(forms.ModelForm, BaseForm):

    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)

    password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput)

    class Meta:
        model = Worker
        fields = ["username", "email", "position"]

    def clean(self):
        """
        Validate attributes, including password constraints, before persisting the user to the database.
        """
        super(WorkerRegisterForm, self).clean()

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 != password2:
            raise forms.ValidationError("You must enter matching passwords.")

        try:
            password_validation.validate_password(
                password=password1, user=get_user_model()
            )
        except exceptions.ValidationError as e:
            raise forms.ValidationError(list(e.messages))

    def save(self, commit=True):
        """
        Save the provided password in hashed format.

        :param commit: If True, changes to the instance will be saved to the database.
        """
        user = super(WorkerRegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data.get("password1"))

        if commit:
            user.save()

        return user

csgo_django_server/task_manager/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic, View
from task_manager.models import Worker
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from task_manager.utils import start_child_processes
from django.conf import settings
from dotenv import load_dotenv
import subprocess
import time
import json
from django.core.files.storage import FileSystemStorage
import os
import psutil
import csv

web_data = settings.WEB_GLOBAL_DATA
load_dotenv()


class LastPurchasesView(View):
    template_name = 'task_manager/last_purchases.html'

    def get(self, request, *args, **kwargs):
        # Read the last 5 lines from the CSV file
        last_purchases = self.get_last_purchases()

        return render(request, self.template_name, {'last_purchases': last_purchases})

    def get_last_purchases(self):
        csv_file_path = os.getenv("PATH_TO_BUY_ITEMS_CSV_DB")  # Update with your actual file path

        # Read the last 5 lines from the CSV file
        with open(csv_file_path, 'r', newline='', encoding='utf-8') as file:
            lines = list(csv.reader(file))
            last_5_lines = lines[-5:]
            print(last_5_lines)

        return last_5_lines


class GetIPView(View):
    def get(self, request):
        client_ip = self.get_client_ip(request)
        request.session['client_ip'] = client_ip
        return JsonResponse({'client_ip': client_ip})

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip


def upload_file(request):
    if request.method == 'POST' and request.FILES['file']:
        uploaded_file = request.FILES['file']
        file_name = uploaded_file.name

        # Specify the target folder
        target_folder = os.getenv("PATH_TO_UPLOAD_DIRECTORY")  # Change this to your desired folder name
        target_folder_path = os.path.join(settings.MEDIA_ROOT, target_folder)

        # Create the target folder if it doesn't exist
        os.makedirs(target_folder_path, exist_ok=True)

        # Check if a file with the same name exists in the target folder
        existing_file_path = os.path.join(target_folder_path, file_name)
        if os.path.exists(existing_file_path):
            os.remove(existing_file_path)

        fs = FileSystemStorage(location=target_folder_path)
        filename = fs.save(file_name, uploaded_file)
        file_url = fs.url(filename)
        return render(request, 'task_manager/upload_file.html', {'file_url': file_url})

    return render(request, 'task_manager/upload_file.html')


@login_required
def save_proxy(request):
    if request.method == 'POST':
        content = request.POST.get('proxy_content', '')
        file_path = os.getenv("PATH_TO_PROXY_LIST")
        with open(file_path, 'w') as file:
            file.write(content)

    return HttpResponseRedirect('/proxy/')


@login_required
def home_view(request):
    file_path = os.getenv("PATH_TO_PROXY_LIST")
    with open(file_path, 'r') as file:
        content = file.read()
    proxy_count = content.count('\n') + 1
    return render(request, 'task_manager/home.html', {'proxy_count': proxy_count})


@login_required
def proxy_view(request):
    # Read the file
    file_path = os.getenv("PATH_TO_PROXY_LIST")
    with open(file_path, 'r') as file:
        content = file.read()
    proxy_count = content.count('\n') + 1
    # Render proxy.html with the file content
    return render(request, 'task_manager/proxy.html', {'proxy_count': proxy_count, 'file_content': content})


@login_required
def items_view(request):
    # Read the file
    file_path = os.getenv("PATH_TO_CONDITIONS")
    with open(file_path, 'r') as file:
        content = file.read()
    # Render proxy.html with the file content
    return render(request, 'task_manager/items.html', {'file_content': content})


def items_save(request):
    if request.method == 'POST':
        content = request.POST.get('items_content', '')
        file_path = os.getenv("PATH_TO_CONDITIONS")
        # Save the edited content back to the file
        with open(file_path, 'w') as file:
            file.write(content)

    return HttpResponseRedirect('/items/')


@login_required
class HomeView(TemplateView):
    template_name = 'task_manager/home.html'

    def form_valid(self, form):
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class ProcessManager:
    def __init__(self):
        pass

    def get_process_status_by_port(self, port):
        for process in psutil.process_iter(['pid', 'name', 'connections']):
            try:
                if process.info and 'name' in process.info and 'python' in process.info['name'].lower():
                    if process.info and 'connections' in process.info and process.info['connections']:
                        for conn in process.info['connections']:
                            if hasattr(conn, 'laddr') and conn.laddr and conn.laddr.port == port:
                                return True  # Процесс найден по порту
            except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
                pass
        return False


class ControlView(View):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.search_main = os.getenv('PATH_TO_SEARCH_MAIN')
        self.listing_main = os.getenv('PATH_TO_LISTING_MAIN')
        self.buy_module_main = os.getenv('PATH_TO_BUY_MODULE_MAIN')

        self.buy_module_venv = os.getenv('PATH_TO_BUY_MODULE_VENV')
        self.listing_module_venv = os.getenv('PATH_TO_LISTING_MODULE_VENV')
        self.search_module_venv = os.getenv('PATH_TO_SEARCH_MODULE_VENV')

        self.processes = [
            (self.search_main, self.search_module_venv, int(os.getenv("SEARCH_PORT")), 3),
            (self.listing_main, self.listing_module_venv, int(os.getenv("LISTING_PORT")), 1),
            (self.buy_module_main, self.buy_module_venv, int(os.getenv("BUY_MODULE_PORT")), 0),
        ]
        self.web_data_update = {
            "proxy_nowork_count": 0,
            "proxy_work_count": 0,
            "proxy_slow": 0,
            "proxy_bad": 0,
            "buy_ok": 0,
            "buy_error": 0,
            "amount_proxies": 0,
        }

    template_name = 'control.html'
    process_manager = ProcessManager()

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        command = request.POST.get('command')

        if command:
            if command == 'start':
                start_child_processes(self.processes)
                return JsonResponse({'status': 'success'})

            elif command in ['stop', 'restart']:
                subprocess.run(['pkill', '-f', self.search_main])
                time.sleep(5)
                subprocess.run(['pkill', '-f', self.listing_main])
                time.sleep(5)
                subprocess.run(['pkill', '-f', self.buy_module_main])
                time.sleep(5)

                if command == 'restart':
                    time.sleep(8)
                    start_child_processes(self.processes)
                    time.sleep(10)

                web_data.update(self.web_data_update)
                return JsonResponse({'status': 'success'})

        return JsonResponse({'status': 'error', 'message': 'Invalid command'})


@csrf_exempt
def update_data(request):
    try:
        if request.method == 'POST':
            try:
                request_data = json.loads(request.body.decode('utf-8'))

                for key in ['proxy_bad', 'proxy_slow', 'balance', 'buy_ok', 'buy_error', 'items_count',
                            'proxy_work_count', 'buy_items', 'listing_proxy_work', 'search_proxy_work',
                            'len_listing_sessions', 'len_search_sessions', 'proxy_nowork_count', 'amount_proxies']:
                    if key in request_data:
                        web_data[key] = request_data[key]

                return JsonResponse(web_data)

            except json.JSONDecodeError:
                return JsonResponse({'error': 'Invalid JSON in request body'}, status=400)
        else:
            return JsonResponse({'error': 'NO POST :( '})

    except Exception as e:
        return JsonResponse({'error': str(e)})


@csrf_exempt
def home_status(request):
    if request.method == 'GET':
        process_manager = ProcessManager()
        web_data['port_8088'] = process_manager.get_process_status_by_port(int(os.getenv("RUN_SERVER_PORT")))
        web_data['port_12352'] = process_manager.get_process_status_by_port(int(os.getenv("SEARCH_PORT")))
        web_data['port_12350'] = process_manager.get_process_status_by_port(int(os.getenv("LISTING_PORT")))
        web_data['port_12351'] = process_manager.get_process_status_by_port(int(os.getenv("BUY_MODULE_PORT")))

        # print(f"GET: SOFT STATUS{web_data}")
        soft_status = web_data.copy()
        if 'buy_items' in web_data:
            del web_data['buy_items']
        return JsonResponse(soft_status)
    else:
        return JsonResponse({'error': 'Invalid request method'})


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, "Logged out successfully.")
        return redirect("login")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    template_name = "task_manager/worker_list.html"
    context_object_name = "worker_list"
    paginate_by = 40

csgo_django_server/templates/task_manager/control.html
<form method="post" action="{% url 'control' %}">
    {% csrf_token %}
    <button type="submit">Запустить процессы</button>
</form>

csgo_django_server/templates/task_manager/items.html
<!-- web/templates/proxy.html -->
{% extends 'base.html' %}

{% block content %}
<div class="col-md-12 col-xl-12 mb-4">

  <form class="col-md-12 col-xl-12 mb-4" method="post" action="{% url 'task_manager:items_save' %}">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">Save</button> <span>Edit Items </span><br><br>
    <textarea id="items_content" name="items_content" style="width: 90%; height: 80vh;">{{ file_content }}</textarea><br>
  </form>

</div>

{% endblock %}

csgo_django_server/templates/task_manager/last_purchases.html
<ul class="list-group">
    {% for purchase in last_purchases %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-3">
                    <strong>{{ purchase.0 }}</strong>
                    <br>
                    <small class="text-muted">{{ purchase.2 }}</small>
                </div>
                <div class="col-md-3">
                    <strong>Float</strong>
                    <br>
                    <small class="text-muted">{{ purchase.3 }}</small>
                </div>
                <div class="col-md-3">
                    <strong>Pattern</strong>
                    <br>
                    <small class="text-muted">{{ purchase.4 }}</small>
                </div>
                <div class="col-md-3">
                    <strong>Price</strong>
                    <br>
                    <small class="text-muted">${{ purchase.1 }}</small>
                </div>
            </div>
        </li>
    {% endfor %}
</ul>

csgo_django_server/templates/task_manager/proxy.html
<!-- web/templates/proxy.html -->
{% extends 'base.html' %}


{% block content %}
<div class="col-md-12 col-xl-12 mb-4">

  <form class="col-md-12 col-xl-12 mb-4" method="post" action="{% url 'task_manager:save_proxy' %}">
  {% csrf_token %}
  <button class="btn btn-primary" type="submit">Save</button> <span>Edit Proxies : <span id="proxy_count_edit">{{proxy_count}}</span></span><br><br>
    <textarea id="proxy_content" name="proxy_content" style="width: 90%; height: 80vh;">{{ file_content }}</textarea><br>

</form>
</div>

<script>
    $('#proxy_content').on('input', function () {

        var textareaValue = $(this).val();
        var lineCount = textareaValue.split(/\r*\n/).length;
        $('#proxy_count_edit').text(lineCount);
    });
</script>

{% endblock %}

csgo_django_server/templates/task_manager/upload_file.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h2 class="text-center">Upload File</h2>

                <form method="post" enctype="multipart/form-data" class="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="file">Choose File:</label>
                        <input type="file" name="file" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>

                {% if file_url %}
                    <p class="mt-3">File uploaded successfully. Here's the link: <a href="{{ file_url }}" target="_blank">{{ file_url }}</a></p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

csgo_django_server/templates/task_manager/worker_detail.html
{% include "base.html" %}

{% block content %}
  <div class="container">
    <div class="row centered">
      <div class="col-lg-3">
        <i class="fa fa-trophy">
          <div class="panel panel-default"><div class="panel-heading">
            <h2 class="text-center">Not started</h2>
          </div></div>
          {% if task_list %}
            {% for task in task_list %}
              {% if task.status == "Not started" %}
                  {% for worker in task.assignees.all %}
                    {% if user.id == worker.id %}
                      {% include "task_manager/task_not_started.html" %}
                    {% endif %}
                  {% endfor %}
              {% endif %}
            {% endfor %}
          {% endif %}
        </i>
      </div>

      <div class="col-lg-3">
        <i class="fa fa-trophy">
          <div class="panel panel-default"><div class="panel-heading">
            <h2 class="text-center">In progress</h2>
          </div></div>
          {% if task_list %}
              {% for task in task_list %}
                {% if task.status == "In progress" %}
                  {% for worker in task.assignees.all %}
                    {% if user.id == worker.id %}
                      {% include "task_manager/task_in_progress.html" %}
                    {% endif %}
                  {% endfor %}
                {% endif %}
              {% endfor %}
          {% endif %}
          </i>
      </div>

      <div class="col-lg-3">
        <i class="fa fa-trophy">
          <div class="panel panel-default"><div class="panel-heading">
            <h2 class="text-center">On review</h2>
          </div></div>
          {% if task_list %}
            {% for task in task_list %}
              {% if task.status == "On review" %}
                {% for worker in task.assignees.all %}
                  {% if user.id == worker.id %}
                    {% include "task_manager/task_on_review.html" %}
                  {% endif %}
                {% endfor %}
              {% endif %}
            {% endfor %}
          {% endif %}
        </i>
      </div>

      <div class="col-lg-3">
        <i class="fa fa-trophy">
          <div class="panel panel-default"><div class="panel-heading">
            <h2 class="text-center">Completed</h2>
          </div></div>
          {% if task_list %}
            {% for task in task_list %}
              {% if task.status == "Completed" %}
                {% for worker in task.assignees.all %}
                  {% if user.id == worker.id %}
                    {% include "task_manager/task_completed.html" %}
                  {% endif %}
                {% endfor %}
              {% endif %}
            {% endfor %}
          {% endif %}
        </i>
      </div>

    </div>
  </div>
  <br>

  <div class="panel-footer position-fixed fixed-bottom"></div>

{% endblock %}

csgo_django_server/templates/task_manager/worker_list.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row centered">
      <i class="fa fa-trophy">
        <h3>Employees</h3>
        {% if worker_list %}
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>ID</th>
                <th>Position</th>
                <th>Full name</th>
                <th>Username</th>
                <th>Email</th>
              </tr>
            </thead>
            <tbody>
              {% for worker in worker_list %}
                <tr>
                  <td>{{ worker.id }}</td>
                  <td>{{ worker.position }}</td>
                  <td>
                    {{ worker.first_name }} {{ worker.last_name }}
                  </td>
                  <td>{{ worker.username }}</td>
                  <td>{{ worker.email }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p>There are no employees</p>
        {% endif %}
      </i>
    </div>
  </div>
  <br>

  <div class="panel-footer position-fixed fixed-bottom"></div>

{% endblock %}